# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 15:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='accDetail',
            fields=[
                ('account_number', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('acc_type', models.CharField(choices=[('Student', 'Student'), ('Saving', 'Saving')], max_length=30)),
                ('amount', models.FloatField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='traDetail',
            fields=[
                ('tra_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('tra_type', models.CharField(choices=[('Withdraw', 'Withdraw'), ('Deposite', 'Deposite')], max_length=30)),
                ('tra_amt', models.FloatField()),
                ('ac_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinebankmanager.accDetail')),
            ],
        ),
        migrations.CreateModel(
            name='UserDataBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=50)),
                ('ans', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('phonumber', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='accdetail',
            name='uname',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='onlinebankmanager.UserDataBase'),
        ),
    ]
